name: Test Suite

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Foundry Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Test
        run: |
          forge test -vvv
        id: test
